main:
	g++ -c helper.cpp
	g++ -c Cell.cpp
	g++ -c AbstractHex.cpp
	g++ -c HexVector.cpp
	g++ -c HexArray1D.cpp
	g++ -c main.cpp
	g++ main.o helper.o Cell.o AbstractHex.o HexVector.o HexArray1D.o -o main